t13

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -13,9 +13,20 @@ jobs:
     runs-on: self-hosted 
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
+      name: Checkout 
+
+    - uses: docker/login-action@v3
+    - name: Dockerhub login
+      with: 
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }} 
+
     - name: Build the Docker image
-      run: docker build . --file Dockerfile --tag mypythonapp:$GITHUB_SHA
+      run: docker build -f Dockerfile -t jrcjoro1/mypythonapp:$GITHUB_SHA . 2> >(while read line; do (>&2 echo "STDERROR: $line"); done)
+
+    - name: Push Docker image to Dockerhub
+      run: docker push jrcjoro1/mypythonapp:$GITHUB_SHA
 
     - name: "Vars"
       run: |
