t27

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -19,6 +19,9 @@ jobs:
       - uses: actions/checkout@v4
         name: Checkout
 
+      - name: Docker version
+        run: docker version
+
       - uses: docker/login-action@v3
         name: Dockerhub login
         with: 
@@ -26,20 +29,10 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }} 
 
       - name: Build the Docker image
-        run: docker build -t jrcjoro1/mypythonapp:$GITHUB_SHA .
+        run: docker build -t jrcjoro1/mypythonapp:$GITHUB_SHA . 2> >(while read line; do (>&2 echo "STDERROR: $line"); done)
 
       - name: Trivy
         run: trivy image --severity HIGH,CRITICAL --format table --exit-code 0 --ignore-unfixed --vuln-type os,library jrcjoro1/mypythonapp:$GITHUB_SHA
-
-#      - uses: aquasecurity/trivy-action@master
-#        name: Run Trivy vulnerability scanner
-#        with:
-#          image-ref: 'jrcjoro1/mypythonapp:${{ github.sha }}'
-#          format: 'table'
-#          exit-code: '1'
-#          ignore-unfixed: true
-#          vuln-type: 'os,library'
-#          severity: 'CRITICAL,HIGH'
 
       - name: Push Docker image to Dockerhub
         run: docker push jrcjoro1/mypythonapp:$GITHUB_SHA
@@ -51,3 +44,4 @@ jobs:
           echo "GITHUB_WORKFLOW_SHA: $GITHUB_WORKFLOW_SHA"
           echo "RUNNER_NAME: $RUNNER_NAME"
           echo "RUNNER_DEBUG: $RUNNER_DEBUG"
+          echo "RUNNER_TEMP: $RUNNER_TEMP"
